config/routes.rb
require 'url_constrainer'

Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'confirm_email', to: 'users/registrations#confirm_email'
  end

  resources :users,               only: [:index] do
    collection do
      get :search
    end
  end

  resources :posts,               except: [:index], param: :url_token do
    resources :comments,          only: [:create, :destroy]
    collection do
      get :search
    end
  end

  resources :relationships,       only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]

  constraints(UrlConstrainer.new) do
    resources :users, param: :username, path: '/', only: [:show, :destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  belongs_to :user
  default_scope -> { order(created_at: :desc) }

  before_validation :generate_url_token, on: :create

  validates :image, presence: true
  validates :caption, length: { maximum: 240 }
  validates :user_id, presence: true
  validates :url_token, presence: true, uniqueness: { case_sensitive: true }

  def to_param
    url_token
  end

  def like(user)
    likes.create(user_id: user.id)
  end

  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end

  def like?(user)
    like_users.include?(user)
  end

  private

  def generate_url_token
    self.url_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[show search]
  before_action :correct_user,       only: %i[edit update destroy]

  def show
    @post = Post.find_by!(url_token: params[:url_token])
    @post_likes = @post.like_users.page(params[:page]).per(24)
    @comments = @post.comments.page(params[:page]).per(24)

    @comment = @post.comments.build
  end

  def new
    @post = current_user.posts.build if user_signed_in?
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = '投稿が送信されました'
      redirect_to user_path(current_user)
    else
      render 'posts/new'
    end
  end

  def edit
    @post = Post.find_by!(url_token: params[:url_token])
  end

  def update
    @post = Post.find_by!(url_token: params[:url_token])
    if @post.update(post_params)
      flash[:success] = '投稿が更新されました'
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    Post.find_by!(url_token: params[:url_token]).destroy
    flash[:success] = '投稿は正常に削除されました'
    redirect_to current_user
  end

  def search
    @q = Post.ransack(params[:q])
    @posts =
      if params[:q].nil?
        @q.result(distinct: true).page(params[:page]).per(24)
      elsif params[:q][:caption_cont].blank?
        Post.none
      else
        @q.result(distinct: true).page(params[:page]).per(24)
      end
  end

  private

  def post_params
    params.require(:post).permit(:image, :image_cache, :caption, :user_id)
  end

  def correct_user
    @post = Post.find_by!(url_token: params[:url_token])
    redirect_to(root_url) unless (@post.user == current_user) || current_user.admin?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<% if comments.any? %>
  <% comments.each do |comment| %>
    <div class="comment d-flex">
      <div class="comment-avatar">
        <% if comment.user.avatar? %>
          <%= link_to image_tag(comment.user.avatar.mini.url, class: "rounded-circle z-depth-0",
                                alt: "avatar image"), user_path(comment.user) %>
        <% else %>
          <%= link_to image_tag("no_user.png", class: "rounded-circle z-depth-0",
                                alt: "avatar image"), user_path(comment.user) %>
        <% end %>
      </div>

      <div class="comment-body">
        <div class="comment-author">
          <%= link_to comment.user.name, user_path(comment.user), class: "author-name" %>
          <%= link_to "@#{comment.user.username}", user_path(comment.user), class: "author-username" %>
        </div>
        <div class="comment-text"><%= comment.content %></div>
        <div class="comment-nav">
          <%= date_format(comment.created_at) %>
          <% if comment.user == current_user %>
            <a class="comment-delete" id="comment-delete-<%= comment.id %>" data-toggle="modal" data-target="#comment_modal_<%= comment.id %>">削除</a>
          <% end %>
        </div>
      </div>

      <%= render 'posts/comment_modal', comment: comment %>

    </div>
  <% end %>
<% else %>
  <div class="no-contents d-flex align-items-center justify-content-center mx-auto">
    まだコメントがありません
  </div>
<% end %>

app/views/posts/_comment_content.html.erb
<div class="comment-content">
  <% if user_signed_in? %>
    <%= form_with(model: @comment, url: post_comments_path(post)) do |f| %>
      <%= hidden_field_tag :post_id, post.id %>
      <div class="comment-editor">
        <%= f.text_area :content, class: "comment", placeholder: "コメントを入力...", id: "paste" %>
        <div class="error-and-btn">
          <div class="comment-error align-items-center mr-2"><span class="mr-1">文字数制限を超えています</span><span id="over"></span></div>
          <div class="btn comment-btn-disable rounded-circle z-depth-0 align-items-center justify-content-center">
            <i class="fas fa-exclamation"></i>
          </div>
          <%= button_tag type: "submit", id: "comment_btn", class: "btn rounded-circle z-depth-0" do %>
            <i class="fas fa-arrow-down"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>

  <div class="comments">
    <%= render 'posts/comment', comments: @comments %>
  </div>
</div>

<script>
  $(function() {
    $('textarea').autosize();

    $('textarea').on("keydown keyup keypress change", function() {
      if ($(this).val().replace(/ +|\n+/g, " ").length < 1) {
        $('.error-and-btn').fadeOut(200);
      } else {
        $('.error-and-btn').fadeIn(100).css('display', 'flex')
      }

      count = $('textarea').val().replace(/ +|\n+/g, " ").length;
      limit = 240 - count
      if (count <= 240) {
        $('#comment_btn').show().css('display', 'flex');
        $('.comment-error').hide();
        $('.comment-btn-disable').hide();
      } else if (count > 240) {
        $('#comment_btn').hide();
        $('.comment-error').show().css('display', 'flex');
        $('#over').text(limit);
        $('.comment-btn-disable').show().css('display', 'flex');
      }
    });
  });

  window.onload = function() {
    var element = document.getElementById("paste");
    element.addEventListener("paste", function(event){
      setTimeout(function(e){
        if ($('textarea').val().replace(/ +|\n+/g, " ").length < 1) {
          $('.error-and-btn').fadeOut(200);
        } else {
          $('.error-and-btn').fadeIn(100).css('display', 'flex');
        }

        count = $('textarea').val().replace(/ +|\n+/g, " ").length;
        limit = 240 - count;
        if (count <= 240) {
          $('#comment_btn').show().css('display', 'flex');
          $('.comment-error').hide();
          $('.comment-btn-disable').hide();
        } else if (count > 240) {
          $('#comment_btn').hide();
          $('.comment-error').show().css('display', 'flex');
          $('#over').text(limit);
          $('.comment-btn-disable').show().css('display', 'flex');
        }
      }, 100, event);
    });
  }
</script>

app/views/posts/_comment_modal.html.erb
<div class="modal" id="comment_modal_<%= comment.id %>" tabindex="-1"
      role="dialog" aria-labelledby="label1" aria-hidden="true">
  <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        コメントを削除しますか？
      </div>
      <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal">キャンセル</button>
        <%= link_to "削除", post_comment_path(comment.post, comment), class: "btn", style: "color: #f90e43;", method: :delete, remote: true, "data-dismiss" => "modal" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_like.html.erb
<%= form_with(model: object.likes.build) do |f| %>
  <div><%= hidden_field_tag :post_id, object.id %></div>
  <%= button_tag(class: "btn like-sm rounded-pill d-flex d-sm-none align-items-center justify-content-center px-3") do %>
    <i class="far fa-thumbs-up" style="font-size: 1.1rem;"></i>
  <% end %>
  <%= button_tag(class: "btn like rounded-pill d-none d-sm-flex align-items-center justify-content-center px-3") do %>
    いいね！<i class="far fa-thumbs-up"></i>
  <% end %>
<% end %>

app/views/posts/_like_form.html.erb
<div class="like-form post-<%= object.id %>">
  <% if object.like?(current_user) %>
    <%= render 'posts/unlike', object: object %>
  <% else %>
    <%= render 'posts/like', object: object %>
  <% end %>
</div>

app/views/posts/_post_footer_links.html.erb
<div class="post-footer-links">
  <a href="<%= post_path(object) %>#comments" style="margin-right: 12px;">
    コメント<%= object.comments.count.to_s(:delimited) %>件
  </a>
  <a href="<%= post_path(object) %>#likes">
    いいね！<span id="likes_<%= object.id %>"><%= object.likes.count.to_s(:delimited) %></span>件
  </a>
</div>

app/views/posts/_post_footer_nav.html.erb
<div class="post-status-cell" id="comments_and_likes">
  <ul class="nav nav-pills justify-content-around" id="pills-tab" role="tablist">
    <li class="nav-item">
      <%= link_to "#", { class: "nav-link d-flex align-items-center justify-content-center px-0", id: "pills-comment-tab", href: "#pills-comment",
          role: "tab", "data-toggle" => "pill", "aria-controls" => "pills-comment", "aria-selected" => "true"} do %>
        <div class="post-status">
          <div class="status-name p-0">コメントの件数</div>
          <div class="status-value" id="comments_<%= object.id %>"><%= object.comments.count.to_s(:delimited) %></div>
        </div>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to "#", { class: "nav-link d-flex align-items-center justify-content-center px-0", id: "pills-like-tab", href: "#pills-like",
          role: "tab", "data-toggle" => "pill", "aria-controls" => "pills-like", "aria-selected" => "true"} do %>
        <div class="post-status">
          <div class="status-name p-0">いいね！された数</div>
          <div class="status-value" id="likes_<%= object.id %>"><%= object.likes.count.to_s(:delimited) %></div>
        </div>
      <% end %>
    </li>
  </ul>
</div>

<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade" id="pills-comment" role="tabpanel" aria-labelledby="pills-comment-tab">
    <%= render 'posts/comment_content', post: object, group: @comments %>
  </div>

  <div class="tab-pane fade" id="pills-like" role="tabpanel" aria-labelledby="pills-like-tab">
  <% if @post_likes.any? %>
    <div class="user-cards post-likes row">
      <%= render 'users/user_cards', group: @post_likes %>
    </div>
    <div class="post-likes-footer">
      <%= paginate @post_likes %>
      <div class="loadmore-btn-wrapper p-0 d-flex">
        <button class="loadmore-btn btn active mx-auto">さらに表示</button>
      </div>
    </div>
  <% else %>
    <div class="no-contents d-flex align-items-center justify-content-center mx-auto">
      まだ "いいね！" がありません
    </div>
  <% end %>
  </div>
</div>

<script>
  $(function () {
    var index = 0;
    var postIndexInit = function() {
      $.cookie('postIndex<%= object.id %>', index);
      $('#pills-tab li:first-child a').addClass('active');
      $('#pills-tabContent .tab-pane:first-child').addClass('show active');
    }

    if (window.performance) {
      if (performance.navigation.type === 1 || performance.navigation.type === 2) {
        if ($.cookie('postIndex<%= object.id %>')) {
          index = $.cookie('postIndex<%= object.id %>');
          $('#pills-tab li a').eq(index).addClass('active');
          $('#pills-tabContent .tab-pane').eq(index).addClass('show active');
        } else { postIndexInit(); }
      } else { postIndexInit(); }
    }

    var urlHash = location.hash;
    if(urlHash === '#comments') {
      $('body,html').stop().scrollTop(0);
      setTimeout(function () {
        //ロード時の処理を待ち、時間差でスクロール実行
        scrollToAnker() ;
      }, 100);
      var hashString = location.hash.substr(1); // remove '#'
      history.replaceState('', document.title, window.location.pathname);
    } else if (urlHash === '#likes') {
      index = 1;
      $('#pills-tab li:first-child a').removeClass('active');
      $('#pills-tabContent .tab-pane:first-child').removeClass('show active');
      $('#pills-tab li a').eq(index).addClass('active');
      $('#pills-tabContent .tab-pane').eq(index).addClass('show active');
      $.cookie('postIndex<%= object.id %>', index)
      $('body,html').stop().scrollTop(0);
      setTimeout(function () {
        //ロード時の処理を待ち、時間差でスクロール実行
        scrollToAnker() ;
      }, 100);
      var hashString = location.hash.substr(1); // remove '#'
      history.replaceState('', document.title, window.location.pathname);
    }

    $('#pills-tab li').click(function() {
      if (index != $('#pills-tab li').index(this)) {
        index = $('#pills-tab li').index(this);
        $.cookie('postIndex<%= object.id %>', index);
      }
      setTimeout(function () {
        //ロード時の処理を待ち、時間差でスクロール実行
        scrollToAnker() ;
      }, 100);

    });

    // 関数：スムーススクロール
    // 指定したアンカー(#ID)へアニメーションでスクロール
    function scrollToAnker() {
      <% if !user_signed_in? %>
        var headerHight = 65;
      <% end %>
      var target = $('#comments_and_likes');
      var position = target.offset().top <% if !user_signed_in? %> -headerHight <% end %>;
      $('body,html').stop().animate({scrollTop:position}, 500);
    }
  });


  $(document).ready(function(){

    function selectTabAndScroll() {
      index = $.cookie('selectTab');
      $('#pills-tab li a').eq(index).addClass('active');
      $('#pills-tabContent .tab-pane').eq(index).addClass('show active');

      //スクロールを0に戻す
      $('body,html').stop().scrollTop(0);
      setTimeout(function () {
        //ロード時の処理を待ち、時間差でスクロール実行
        scrollToAnker('#comments_and_likes') ;
      }, 100);
    }

  })
</script>

app/views/posts/_post_header.html.erb
<div class="post-header d-flex align-items-center">
  <% if object.user.avatar? %>
    <%= link_to image_tag(object.user.avatar.mini.url, size: "50x50", class: "rounded-circle z-depth-0",
                          alt: "avatar image"), user_path(object.user), class: "mr-3" %>
  <% else %>
    <%= link_to image_tag("no_user.png", size: "50x50", class: "rounded-circle z-depth-0",
                          alt: "avatar image"), user_path(object.user), class: "mr-3" %>
  <% end %>
  <div class="post-header-names mr-auto" style="line-height: 20px;">
    <%= link_to object.user.name, user_path(object.user), class: "post-header-name" %><br>
    <%= link_to "@#{object.user.username}", user_path(object.user), class: "post-header-username" %>
  </div>

  <% if user_signed_in? %>
    <% if object.user == current_user %>
      <div class="dropdown mr-1">
        <button type="button" class="btn dropdown-toggle setting-btn py-0 px-1", data-toggle="dropdown", data-offset="0,10", id="post-dropdown-<%= object.id %>",
                          aria-haspopup="true", aria-expanded="false", style="box-shadow: none" ><i class="fas fa-ellipsis-h"></i></button>
        <div class="dropdown-menu dropdown-menu-right">
          <a href="https://twitter.com/share?url=<%= post_url(object) %>" target="_blank" rel="nofollow" class="dropdown-item opensub d-flex align-items-center">
            <div style="width: 100%">投稿を共有</div><i class="fab fa-twitter" style="position: relative; left: 2px;"></i>
          </a>

          <div class="dropdown-divider"></div>
          <%= link_to edit_post_path(object), class: "dropdown-item d-flex align-items-center" do %>
            <div style="width: 100%">投稿を編集</div><i class="far fa-edit" style="position: relative; left: 4px;"></i>
          <% end %>

          <div class="dropdown-divider"></div>
          <a class="dropdown-item d-flex align-items-center" id="post-dropdown-delete-<%= object.id %>" style="color: #f90e43; cursor: pointer;" data-toggle="modal" data-target="#post_modal_<%= object.id %>">
            <div style="width: 100%">投稿を削除</div><i class="fas fa-trash-alt"></i>
          </a>
        </div>
      </div>
    <% elsif current_user.admin?  %>
      <div class="dropdown mr-1">
        <button type="button" class="btn dropdown-toggle setting-btn py-0 px-1", data-toggle="dropdown", data-offset="0,10",
                          aria-haspopup="true", aria-expanded="false", style="box-shadow: none" ><i class="fas fa-ellipsis-h"></i></button>
        <div class="dropdown-menu dropdown-menu-right">
          <a class="dropdown-item d-flex align-items-center" style="color: #f90e43; cursor: pointer;" data-toggle="modal" data-target="#post_modal_<%= object.id %>">
            <div style="width: 100%">投稿を削除</div><i class="fas fa-trash-alt"></i>
          </a>
        </div>
      </div>
    <% else %>
      <div class="dropdown d-block d-sm-none" style="margin-right: 15px;">
        <button type="button" class="btn dropdown-toggle setting-btn py-0 px-1", data-toggle="dropdown", data-offset="51,10",
                          aria-haspopup="true", aria-expanded="false", style="box-shadow: none" ><i class="fas fa-ellipsis-h"></i></button>
        <div class="dropdown-menu dropdown-menu-right">
          <a href="https://twitter.com/share?url=<%= post_url(object) %>" target="_blank" rel="nofollow" class="dropdown-item opensub d-flex align-items-center">
            <div style="width: 100%">投稿を共有</div><i class="fab fa-twitter" style="position: relative; left: 2px;"></i>
          </a>
        </div>
      </div>
      <div class="dropdown d-none d-sm-block" style="margin-right: 15px;">
        <button type="button" class="btn dropdown-toggle setting-btn py-0 px-1", data-toggle="dropdown", data-offset="-18,10",
                          aria-haspopup="true", aria-expanded="false", style="box-shadow: none" ><i class="fas fa-ellipsis-h"></i></button>
        <div class="dropdown-menu dropdown-menu-left">
          <a href="https://twitter.com/share?url=<%= post_url(object) %>" target="_blank" rel="nofollow" class="dropdown-item opensub d-flex align-items-center">
            <div style="width: 100%">投稿を共有</div><i class="fab fa-twitter" style="position: relative; left: 2px;"></i>
          </a>
        </div>
      </div>
      <%= render 'posts/like_form', object: object %>
    <% end %>
  <% else %>
    <div class="dropdown mr-1">
      <button type="button" class="btn dropdown-toggle setting-btn py-0 px-1", data-toggle="dropdown", data-offset="0,10",
                        aria-haspopup="true", aria-expanded="false", style="box-shadow: none" ><i class="fas fa-ellipsis-h"></i></button>
      <div class="dropdown-menu dropdown-menu-right">
        <a href="https://twitter.com/share?url=<%= post_url(object) %>" target="_blank" rel="nofollow" class="dropdown-item opensub d-flex align-items-center">
          <div style="width: 100%">投稿を共有</div><i class="fab fa-twitter" style="position: relative; left: 2px;"></i>
        </a>
      </div>
    </div>
  <% end %>
</div>

<script>
  jQuery(document).ready(function(){
    $(".opensub").click(function(){
      window.open(this.href,"WindowName","width=520,height=350,resizable=yes,scrollbars=yes");
      return false;
    });
  });
</script>

app/views/posts/_post_modal.html.erb
<div class="modal" id="post_modal_<%= object.id %>" tabindex="-1"
      role="dialog" aria-labelledby="label1" aria-hidden="true">
  <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        投稿を削除しますか？
      </div>
      <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal">キャンセル</button>
        <%= link_to "削除", post_path(object), class: "btn", style: "color: #f90e43;", method: :delete %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_unlike.html.erb
<%= form_with model: object.likes.find_by(user_id: current_user.id), html: { method: :delete } do |f| %>
  <div><%= hidden_field_tag :post_id, object.id %></div>
  <%= button_tag(class: "btn unlike-sm rounded-pill d-flex d-sm-none align-items-center justify-content-center px-3") do %>
    <i class="fas fa-check" style="font-size: 1.1rem; position: relative; top: 1px;"></i>
  <% end %>
  <%= f.submit "いいね！済み", class: "btn unlike rounded-pill d-none d-sm-flex align-items-center justify-content-center px-3" %>
<% end %>

app/views/posts/edit.html.erb
<% provide :title, "投稿を編集" %>

<div class="page-header d-flex align-items-center mx-auto mb-4">投稿を編集</div>

<%= form_for @post do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="post-form">
    <div class="preview-wrap" onClick="$('#file').click()">
      <div id="img_field">
        <% if @post.image.url.present? %>
          <%= image_tag(@post.image.url, class: "preview") %>
        <% end %>
      </div>
      <i class="fas fa-camera" onClick="$('#file').click()"></i>
    </div>

    <%= f.file_field :image, class: "image", style: "display: none;", id: "file", accept: 'image/jpeg,image/gif,image/png' %>
    <%= f.hidden_field :image_cache %>


    <%= f.text_area :caption, class: "caption", placeholder: "キャプションを入力..." %>


  </div>

  <div class="post-form-btns text-right mb-4">
    <%= link_to "キャンセル", root_path, class: "btn post-form-btn mr-2", style: "border: none;" %>
    <%= f.submit "投稿を送信", { class: "btn post-form-btn mr-3" } %>
  </div>
<% end %>

<%= render 'posts/post_form_script' %>

app/views/posts/new.html.erb
<% provide :title, "新規投稿" %>

<div class="page-header d-flex align-items-center mx-auto mb-4">新しい投稿</div>

<%= form_for @post do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="post-form">
    <div class="preview-wrap" onClick="$('#file').click()">
      <div id="img_field">
        <% if @post.image.url.present? %>
          <%= image_tag(@post.image.url, class: "preview") %>
        <% end %>
      </div>
      <i class="fas fa-camera" onClick="$('#file').click()"></i>
    </div>

    <%= f.file_field :image, class: "image", style: "display: none;", id: "file", accept: 'image/jpeg,image/gif,image/png' %>
    <%= f.hidden_field :image_cache %>


    <%= f.text_area :caption, class: "caption", placeholder: "キャプションを入力..." %>


  </div>

  <div class="post-form-btns text-right mb-4">
    <%= link_to "キャンセル", root_path, class: "btn post-form-btn mr-2", style: "border: none;" %>
    <%= f.submit "投稿を送信", { class: "btn post-form-btn mr-3" } %>
  </div>
<% end %>

<%= render 'posts/post_form_script' %>

app/views/posts/search.html.erb
<div class="search-form mx-auto">
  <div class="field form-group">
    <%= search_form_for(@q, url: search_posts_path) do |f| %>
      <div class="input-group">
        <% f.label :caption_cont %>
        <%= f.search_field :caption_cont, class: "form-control", placeholder: "投稿を検索" %>
      </div>
    <% end %>
  </div>

  <ul class="nav nav-pills">
    <li class="nav-item">
      <a class="nav-link active" href="#">投稿</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= search_users_path %>">ユーザー</a>
    </li>
  </ul>
</div>

<% if @posts.any? %>
  <div class="search-posts-container">
    <div class="post-cards search row">
      <% @posts.each do |post| %>
        <div class="post-card col-6 col-sm-4">
          <div class="post-card-img">
            <%= link_to image_tag(post.image.url, class: "img-fluid", alt: "post image"), post_path(post) %>
          </div>
          <div class="post-card-footer d-flex align-items-center">
            <% if post.user.avatar?%>
              <%= link_to image_tag(post.user.avatar.mini.url, size: "35x35", class: "rounded-circle z-depth-0",
                                    alt: "avatar image"), user_path(post.user), class: "mr-3" %>
            <% else %>
              <%= link_to image_tag("no_user.png", size: "35x35", class: "rounded-circle z-depth-0",
                                    alt: "avatar image"), user_path(post.user), class: "mr-3" %>
            <% end %>
            <div class="post-footer-names" style="line-height: 20px;">
              <%= link_to post.user.name, user_path(post.user), class: "post-footer-name" %><br>
              <%= link_to "@#{post.user.username}", user_path(post.user), class: "post-footer-username" %></a>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="post-cards-footer search">
      <%= paginate @posts %>
      <div class="loadmore-btn-wrapper p-0 d-flex">
        <button class="loadmore-btn btn active mx-auto">さらに表示</button>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<% provide :url, post_url(@post) %>
<% provide :caption, @post.caption %>
<% provide :image, @post.image.url %>

<%= render 'layouts/toast' %>

<div class="post-container no-gutters mx-sm-auto" style="max-width: 700px">
  <%= render 'posts/post_header', object: @post %>
  <div class="col img-col">
    <%= image_tag @post.image.url, size: "1100x1100", class: "img-fluid" %>
  </div>
  <div class="col">
    <%= render 'posts/post_body', object: @post %>
    <%= render 'posts/post_footer_nav', object: @post %>
  </div>
</div>

<%= render 'posts/post_modal', object: @post %>