config/routes.rb
require 'url_constrainer'

Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'confirm_email', to: 'users/registrations#confirm_email'
  end

  resources :users,               only: [:index] do
    collection do
      get :search
    end
  end

  resources :posts,               except: [:index], param: :url_token do
    resources :comments,          only: [:create, :destroy]
    collection do
      get :search
    end
  end

  resources :relationships,       only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]

  constraints(UrlConstrainer.new) do
    resources :users, param: :username, path: '/', only: [:show, :destroy]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/_footer.html.erb
<footer class="d-flex align-items-center justify-content-center">
    <p class="text-center"><small>Copyright &copy;2019 <%= website_name %>, All Rights Reserved.</small></p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand navbar-light mb-3">
  <div class="container">
    <%= link_to website_name, root_path, class: "navbar-brand font-weight-bold" %>
    <%= link_to search_posts_path, class: "navbar-search-btn" do %><i class="fas fa-search"></i><% end %>
    <%= link_to users_path, class: "navbar-users nav-item nav-link active px-0 mr-1" do %>
      <i class="fas fa-user-friends" style="font-size: 1.1rem; position: relative; top: 1px; left: 3px;"></i>
    <% end %>
    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item d-flex align-items-center">
            <%= link_to user_path(current_user), class: "avatar-user-name nav-link mr-3 p-0" do %>
              <div class="nav-username d-none d-sm-flex"><div style="font-size: 1.05rem;">@</div><div class="nav-username-text"><%= current_user.username %></div></div>
            <% end %>
            <% if current_user.avatar?%>
              <%= link_to image_tag(current_user.avatar.mini.url, class: "avatar-img rounded-circle z-depth-0",
                                    alt: "nav avatar image"), user_path(current_user), class: "nav-link p-0" %>
            <% else %>
              <%= link_to image_tag("no_user.png", class: "avatar-img rounded-circle z-depth-0",
                                    alt: "nav avatar image"), user_path(current_user), class: "nav-link p-0" %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_post_path, class: "btn btn-dark nav-btn", style: "background-color: #23272b; position: relative; left: 1px;" do %><i class="far fa-edit mr-1"></i>投稿<% end %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link active px-0 mr-sm-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: "btn btn-white nav-btn" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
 

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="content-language" content="ja" charset="utf-8">

<!-- FontAwesome -->
<link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/jquery-autosize@1.18.18/jquery.autosize.min.js"></script>

<!-- OGP設定 -->
<meta name="twitter:card" content="summary">
<meta property="og:title" content="Mewblr">
<meta property="og:url" content="<%= yield(:url) %>">
<meta property="og:description" content="<%= !yield(:caption).blank? ? yield(:caption) : "友達と写真やアートを共有しよう。" %>">
<meta property="og:image" content="<%= !yield(:image).blank? ? yield(:image) : asset_url("mewblr.jpg") %>">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_signin_as_guest.html.erb
<%= link_to "#", "data-toggle" => "modal", "data-target" => "#signin_as_guest_modal" do %>
  <nav class="navbar signin-as-guest fixed-top d-flex justify-content-center align-items-center">
    <div>すぐに全機能をお試しになりたい場合は、<div class="d-inline" style="font-weight: 800">こちらからゲストユーザーとしてログインできます。</div></div>
  </nav>
<% end %>
<div class="pt-65"></div>

<div class="modal" id="signin_as_guest_modal" tabindex="-1"
    　role="dialog" aria-labelledby="label1" aria-hidden="true">
  <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        ゲストユーザーとしてログインしますか？
      </div>
      <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal">キャンセル</button>


        <%= form_for(User.new, as: :user, url: session_path(:user)) do |f| %>
          <%= f.hidden_field :login, value: "guest" %>
          <%= f.hidden_field :password, value: "123456" %>
          <%= f.submit "ログイン", class: "btn", style: "color: #f90e43;" %> 
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_toast.html.erb
<% if flash[:success]%>
  <nav class="fixed-bottom toast mx-auto mb-sm-4" style="background-color: #fc8023" data-delay="3000">
    <div class="toast-body d-flex align-items-center p-2">
      <div class="mx-auto font-weight-bold"  style="color: #fff; font-size: 1rem;"><%= flash[:success]%></div>
    </div>
  </nav>

  <script>
  $('.toast')
    .toast({
      autohide: true
    })
    .toast('show')
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <% unless user_signed_in? %>
      <%= render 'layouts/signin_as_guest' %>
    <% end %>
    <%= render 'layouts/header' %>
    <div class="container mb-5">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>  
  </body>
</html>